KS-13-3-telephone-directory-list
kotatka/KotlinSprint pull request #68
Opened 2024-10-14 09:06 UTC by kotatka

2024-10-15 09:54 UTC, ievetrovdev requested changes

2024-10-15 09:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +    val listContacts =
Согласно ТЗ необходимо создать контакты и инициализировать список сразу, без дополнительных переменных, к тому же, сейчас у тебя выводятся все контакты, а нужно только те, в которых поле company не пустое, чтобы это реализовать, посмотри в сторону `mapNotNull`

2024-10-15 09:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +        if (nameCompany == null) println("Имя:$nameUser, Номер:$telephoneNumber, Компания:<Не указано>")
Какой более короткий оператор выполняет ту же функцию, что и if else, но занимает всего 2 символа?

2024-10-15 10:21 UTC, kotatka commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +    val listContacts =
В задании написано: Выведи список всех существующих компаний в телефонной книге, а не список всех контактов у который есть компания

2024-10-15 10:27 UTC, kotatka commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +    val listContacts =
Но задача показалась мне интересной, поэтому выполню и её:)

2024-10-15 18:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +    val listContacts =
> В задании написано: Выведи список всех существующих компаний в телефонной книге, а не список всех контактов у который есть компания

Если вчитаться в эту формулировку, то можно понять, что контакты, у которых поле компании не заполнено выводить не нужно, что не соблюдалось в предыдущем решении, в котором выводились вообще все контакты

2024-10-15 18:57 UTC, ievetrovdev requested changes

2024-10-15 18:57 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +    val numbersCompanies = listContacts.filter { it.nameCompany!=null }
mapNotNull уже возвращает отфильтрованный список без null, поэтому дополнительная фильтрация избыточна

Не забывай прожимать автоформатирование перед коммитом. по коду в паре мест не хватает пробелов Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx)

2024-10-15 18:57 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +    println(allCompanies)
Давай пользоваться красивым выводом с помощью `forEach`

2024-10-15 18:57 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +println(listContacts)
В задании не требуется выводить список всех контактов

2024-10-15 18:57 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task3_telephone_directory_list.kt
> +        val correctName = nameCompany?.toString() ?: ("<Не указано>")
null не нужно приводить к строке, с помощью элвис оператора мы обрабатываем нулябельность, к тому же это все можно делать короче при выводе без дополнительной переменной

2024-10-17 18:11 UTC, ievetrovdev approved these changes

2024-10-18 09:13 UTC, merged